#pragma once

#include <memory>

namespace HOL::hacks
{
	// Owns a patch in OVRServer's memory, allowing background tracking for this app's PID.
	// The exception keeps all of this app's focus-controlled state groups enabled,
	// without changing focus ownership or permission decisions for other clients.
	// The server-patch lifetime follows one HandOfLesser tracking run:
	//   install() before OpenXR initialization -> use tracking -> restore() on shutdown.
	class OvrServerTrackingPatch
	{
	public:
		OvrServerTrackingPatch();
		~OvrServerTrackingPatch();
		OvrServerTrackingPatch(const OvrServerTrackingPatch&) = delete;
		OvrServerTrackingPatch& operator=(const OvrServerTrackingPatch&) = delete;
		// Find the server/check and install a scoped jump to our generated code.
		// A recognized patch retained after forced app exit is restored first, provided
		// its owner has exited; the new patch then targets this process's PID.
		// Returns false and logs the error if installation cannot be completed.
		bool install();

		// Restore the original check before freeing our remote code. Also called by the
		// destructor and failed-install cleanup; repeated calls after success are harmless.
		void restore() noexcept;

	private:
		// Implementation details live in the .cpp: Windows handles, remote addresses,
		// generated bytes, and the information needed to undo a partially completed install.
		struct Impl;
		std::unique_ptr<Impl> mImpl;
	};
} // namespace HOL::hacks
